# Generated by Django 4.2.5 on 2023-09-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('instrument', models.CharField(choices=[('v', 'Vocals'), ('g', 'Guitar'), ('b', 'Bass'), ('d', 'Drums'), ('k', 'Keys'), ('o', 'Other')], default='v', max_length=1, verbose_name='Primary Instrument')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.band')),
            ],
        ),
    ]
